# Generated by Django 5.1.4 on 2024-12-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchantId', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
